sudo: false
env:
  global:
  - PATH="$HOME/.local/bin:$PATH"
  - OPA_VERSION=0.21.0
  - TERRAFORM_VERSION=0.12.18
  - TF_IN_AUTOMATION=true
  - REGULA_VERSION=v0.4.0
  - REGULA_DIR="$HOME/.local/bin/regula"
  # AWS_ACCESS_KEY_ID
  - secure: "Z2iYEVPKsAtrPAOoutWqK20vxOac8CKnosQbjn/xVF9wPSOFZvtoem8Te6269CfBS8qH46lHXUoHLTcXxvUkKQFfgMCytBKhimMtaat0cjOKYmsbtufkVrGVd7kqnBekWhFfvsJ8EgUPqdA3DglCRxami4HUJsvI+K6UNveE4Pk+E5lCDTjDVyBcOIkfbuEbADvIXs+ly5kfr6DMkX3Q71gQTA1a+hajVKm1VkMoBbNvRkZYzP1AzFYgX+OTQyyvcqjeKqRZl95FUS0KzvTLwudS1knKUHntq7O4uqG/EVzo2GHx2RSj/uU0wuz5lsdx2p7rQ/expwIxxEIGRC8JdyQpuUDTCMXwKQEJDXEcNPA+zHbFSYok12yuElUYCx3xUZywB8AYRdTrY+JlLti2proUz6ViIbOvbi6yeHfGx3iFeECDhh/IB46cead0jNTT99NNUef1+x/iOiOy4427wXF/AwidVXhkReFKE6dT5kxplOMglEWJkk0Vgg0cegBaTlWo4aQEdPve0gTN2coFPxrPZ34t/Uc7shLoF+j4ejcsN5EIJJ0Me23D+zzp16XcTzdPjllVE2jAipJi/DImKb/MjUrnnji1w0xbPcKM0/YWmqdPyVCAWDxP344WvFr42mXY/vPHl0H3VKNs0/zcHqTgSOPO9XHa9LV2BWx+t6o="
  # AWS_SECRET_ACCESS_KEY
  - secure: "DW39Dmwi0rYcafuiT+Af3FuUtuBh7L7QEMaGZrZnF8lYr2CuNJWNH94of5hZ+9HHiEQ2ICgkHafJm/zWnqBw3nM5MsQFHXYTggt4lQ4VfRrx19PkcnoDdVX1gFVSxPXN9GeJ9IJ9I7oqVCzvl1KwfgOA7zzAFZ020ZPGpT7x28/DHiY0Av5b3OGPhKwyvm95Nzprliqed3G4jAiJOIDaF3Z2xwMq5lhHdrkAcyRaRSuXJuFCkWhPnov+MD9rxtJBl2IbwWNRJEnnxrAK1hls6XGKRdsbk8R7nTBUoWGnu4CxW5lCF3nxGL4y37Bo+ougrjz4g1VYftTCm3qhwdtNafv+khC/M6+g0haByU9xe2hhF1Evr37KoHXdmrP/Wq+Ba+DGKoD0sAZRNRQS+er/cvaIvwVQPnqBCAuwR1vSIE7kkaDUHetUfgIURsbqCNvQQDQSq5kCsFUnzCswQ26d9qWW65UCkKYu8QTutCmVVgTdPzcuWdFHBkfWqePgZAyv8jrM0jhQy8E+0dCDvTBT1jx3e5vCUt1myCzUd8mIBiNTK8opTqHUYdRWobQPegBAn+cx09+Lzuro1PHJtPKYrz3TUPp4kk91BLRRjRETrewwwxWQ5w9JMQ9+pqkqn7BHBWoWq+I6biJZWMsBdJeOrUbxYBwrh24b91EU/fyT84c="

before_script:
- mkdir "$HOME/.local/bin"

# Install OPA
- curl -Lo "$HOME/.local/bin/opa" "https://github.com/open-policy-agent/opa/releases/download/v$OPA_VERSION/opa_linux_amd64"
- chmod +x "$HOME/.local/bin/opa"

# Install terraform.
- curl -Lo "/tmp/terraform-$TERRAFORM_VERSION.zip" "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip -d "$HOME/.local/bin/" "/tmp/terraform-$TERRAFORM_VERSION.zip"

# Install regula script and libraries.
- mkdir "$REGULA_DIR"
- curl -L "https://github.com/fugue/regula/archive/$REGULA_VERSION.tar.gz" | tar -xvz --strip-components=1 -C "$REGULA_DIR"

script:
# Run regula
- REGULA_OUTPUT="$(mktemp)"
- $REGULA_DIR/bin/regula infra_tf $REGULA_DIR/lib $REGULA_DIR/rules example_custom_rule >"$REGULA_OUTPUT"
- REGULA_VALID="$(jq -r '.result[0].expressions[0].value.summary.valid' "$REGULA_OUTPUT")"
- jq -r '.result[0].expressions[0].value.message' "$REGULA_OUTPUT" >&2
- if [[ "$REGULA_VALID" != "true" ]]; then exit 1; fi
