sudo: false
env:
  global:
  - PATH="$HOME/.local/bin:$PATH"
  - OPA_VERSION=0.15.1
  - TERRAFORM_VERSION=0.12.18
  - TF_IN_AUTOMATION=true
  - REGULA_VERSION=report-message
  - REGULA_DIR="$HOME/.local/bin/regula"
  - secure: raBxk05UDtYvP0109Q4QA4kbNhUySRpBlCw4z5u2kKWo05n1Gn0PvDIcK+Nq4I1mUlJAROYKBTI1H4LVaXZjb2qw1asXqUUIX6e6F2+SXDamajLuRuyeNiqhgGw4rO77LXaswURXdsS0YkeN1EE/AxG2/K42+aszBOWmkXcTmvtSpFNQQFtXINIKY7fN26RIYDBFWUdvrxgDG1OjK4X8Ww0Zr4BlSfwZCNpCFEbqGU1hlLXO/iB45g1QIJ+RFLTeWBQJbmfg9d5YX98pzDxDQYQ3z93IQp/AmJz4PMfHNZn79PCOj+pfCPTk0nCNUFhN5DAu+/8NbdovDxKG/06DtZAU4FREDqB1Jix6XKZq/hybqfIMMKiRE2Qal4h6TkTp2FV1j7h2UaKIEP0nO1gXgYLsQr6c8fFKY57NCHDvg7laMcmn7/ILYkMVV83xOfsuL1OJg6HPK/4aZI4TwvhpN+Gc/R4PrWoi3/99tKwv6UuoYHMj4vC+9ZR5ABQ4J7zj5K3nGteTA5dhV3p290RCbQuaYGJH8HeYNXyGNA1FEmKH1DNZNwsUuWO57cRSum9+RCm/LcrGTYSRdqYtutQmH5qELUxbVkzHirTY4NXrWvPQC3KUzdm0zKTWm/4ISyaocfuOMJPrXkWQvmLZWVsFlGkCvTiK0BK7tE1jUBIGR2Q=
  - secure: dDv9H9/zYD93lMIGPmshs6gU9+gsopMxs/H6Uc6UaSWMFEJFBrMZ+LEonsYXxbNc+8fodqzeEjhaEHkvmxJxHwEETSgxNXY+2MmjFHggYuaq3JwVFLrDrc5OwtjCorY6I/lV5qBr/OVwK16ERAzfz/NK2p8vRW2tquTd07iZZcbBXowyKNO51/2fqsKwH4+hbQER23vWXMFsBmYpgAAsJPOnoUU5mQdLf538BWpCF2IZzGRFpXrPIjm1Xa6AsNKmrFiD0nw88VcNhigqBkoGFWuf9q3TR++icsfCzUQI/jg6KVxgbK66OylZ3X7e4na4rF0UWUmeNLQcjvL6g5VK7xED+zdArwFm+fqo4ow3+hK1FEcmIAMzAakDIU3mPvnKmRMHzeM77a0SAMl0Gwsm7s/eA7G3B5ork14LaTX0EFnsM6fwYCeDQncZ+C4XpLYqxtu1/Ki6rtsIhFts0s7cfOmA0FOnlTGLDFl4aWNLO3e3Kdd9bMN5ugrldZeBOQoMX+lX+pzXbGs3D0vSzbq5lP3C/+WO+RUCLklwzBZwDqelaYEQYER/qrEA9/yFVlLlEbvrPTctJ/jkOIjpmm2kvEbLR0sC+T8GYoqut6/ChDqIdnjT33dc98Zu7cPhHQiYddCvKz7DQBG/iDPwclLd0o4rvIxguXp7m/wOozb8CKU=

before_script:
- mkdir "$HOME/.local/bin"

# Install OPA
- curl -Lo "$HOME/.local/bin/opa" "https://github.com/open-policy-agent/opa/releases/download/v$OPA_VERSION/opa_linux_amd64"
- chmod +x "$HOME/.local/bin/opa"

# Install terraform.
- curl -Lo "/tmp/terraform-$TERRAFORM_VERSION.zip" "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip -d "$HOME/.local/bin/" "/tmp/terraform-$TERRAFORM_VERSION.zip"

# Install regula script and libraries.
- mkdir "$REGULA_DIR"
- curl -L "https://github.com/fugue/regula/archive/$REGULA_VERSION.tar.gz" | tar -xvz --strip-components=1 -C "$REGULA_DIR"

script:
# Run regula
- REGULA_OUTPUT="$(mktemp)"
- $REGULA_DIR/bin/regula . $REGULA_DIR/lib $REGULA_DIR/rules example_custom_rule >"$REGULA_OUTPUT"
- REGULA_VALID="$(jq -r '.result[0].expressions[0].value.summary.valid' "$REGULA_OUTPUT")"
- jq -r '.result[0].expressions[0].value.message' "$REGULA_OUTPUT" >&2
- if [[ "$REGULA_VALID" != "true" ]]; then exit 1; fi
