AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ValidRole01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ['ec2.amazonaws.com']
          Action:
          - sts:AssumeRole

  ValidPolicy01:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
      - !Ref ValidRole01
      PolicyName: valid_policy_01
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - 'ec2:StartInstances'
          Resource:
          - '*'
