on: [push]

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@7dc08e11e402f0bcf7497d0349c3f9798670209a
      with:
        input_path: infra_tf
        rego_paths: /opt/regula/rules example_custom_rule
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  regula_cfn_job:
    runs-on: ubuntu-latest
    name: Regula CloudFormation
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@7dc08e11e402f0bcf7497d0349c3f9798670209a
      with:
        input_path: infra_cfn/cloudformation.yaml
        rego_paths: /opt/regula/rules

  regula_valid_cfn_job:
    runs-on: ubuntu-latest
    name: Regula Valid CloudFormation
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@7dc08e11e402f0bcf7497d0349c3f9798670209a
      with:
        input_path: infra_valid_cfn/cloudformation.yaml
        rego_paths: /opt/regula/rules

  regula_multi_cfn_job:
    runs-on: ubuntu-latest
    name: Regula multiple CloudFormation templates
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@7dc08e11e402f0bcf7497d0349c3f9798670209a
      with:
        input_path: '*/cloudformation.yaml'
        rego_paths: /opt/regula/rules
