on: [push]

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@996f358972ac9252dd776becc36af1d962bf4d72
      with:
        input_path: infra_tf
        rego_paths: /opt/regula/rules example_custom_rule
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  regula_cfn_job:
    runs-on: ubuntu-latest
    name: Regula CloudFormation
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@996f358972ac9252dd776becc36af1d962bf4d72
      with:
        input_path: infra_cfn/cloudformation.yaml
        rego_paths: /opt/regula/rules

  regula_valid_cfn_job:
    runs-on: ubuntu-latest
    name: Regula CloudFormation
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@996f358972ac9252dd776becc36af1d962bf4d72
      with:
        input_path: infra_valid_cfn/cloudformation.yaml
        rego_paths: /opt/regula/rules
